output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               macros/,\
               functions.html,\
               build.properties,\
               about.jpg,\
               README.md,\
               IJ_Props.txt,\
               .classpath
source.. = src/
